### ISSUE TITLE
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'

### ISSUE THREAD

**Issue by momingh** [pytorch/FBGEMM#2532]
I ran into the following issues on an NVIDIA 3090GPU. Does fbgemm not support 3090?
```
libcudart.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/mominghao/generative-recommenders-main/train.py", line 32, in <module>
    import fbgemm_gpu
  File "/root/anaconda3/envs/torch/lib/python3.10/site-packages/fbgemm_gpu/__init__.py", line 23, in <module>
    from . import _fbgemm_gpu_docs, sparse_ops  # noqa: F401, E402  # noqa: F401, E402
  File "/root/anaconda3/envs/torch/lib/python3.10/site-packages/fbgemm_gpu/_fbgemm_gpu_docs.py", line 19, in <module>
    torch.ops.fbgemm.jagged_2d_to_dense,
  File "/root/anaconda3/envs/torch/lib/python3.10/site-packages/torch/_ops.py", line 822, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'
```

Here is a list of my environments.  My installation of pytorch is not the night version.
```
absl-py==2.1.0
anykeystore==0.2
apex==0.9.10.dev0
attrs==23.2.0
certifi==2024.2.2
charset-normalizer==3.3.2
contourpy==1.2.1
cryptacular==1.6.2
cycler==0.12.1
defusedxml==0.7.1
exceptiongroup==1.2.1
fbgemm-gpu==0.6.0
filelock==3.9.0
fonttools==4.51.0
fsspec==2023.4.0
fvcore==0.1.5.post20221221
gin==0.1.6
gin-config==0.5.0
greenlet==3.0.3
grpcio==1.62.2
hupper==1.12.1
hypothesis==6.100.1
idna==3.7
iopath==0.1.10
Jinja2==3.1.2
joblib==1.4.0
kiwisolver==1.4.5
Markdown==3.6
MarkupSafe==2.1.3
matplotlib==3.8.4
mpmath==1.3.0
networkx==3.2.1
numpy==1.26.3
nvidia-cublas-cu11==11.11.3.6
nvidia-cuda-cupti-cu11==11.8.87
nvidia-cuda-nvrtc-cu11==11.8.89
nvidia-cuda-runtime-cu11==11.8.89
nvidia-cudnn-cu11==8.7.0.84
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.3.0.86
nvidia-cusolver-cu11==11.4.1.48
nvidia-cusparse-cu11==11.7.5.86
nvidia-nccl-cu11==2.19.3
nvidia-nvtx-cu11==11.8.86
oauthlib==3.2.2
packaging==24.0
pandas==2.2.2
PasteDeploy==3.1.0
pbkdf2==1.3
pillow==10.2.0
plaster==1.1.2
plaster-pastedeploy==1.0.1
portalocker==2.8.2
protobuf==5.26.1
pyparsing==3.1.2
pyramid==2.0.2
pyramid-mailer==0.15.1
python-dateutil==2.9.0.post0
python3-openid==3.2.0
pytz==2024.1
PyYAML==6.0.1
repoze.sendmail==4.4.1
requests==2.31.0
requests-oauthlib==2.0.0
scikit-learn==1.4.2
scipy==1.13.0
six==1.16.0
sortedcontainers==2.4.0
SQLAlchemy==2.0.29
sympy==1.12
tabulate==0.9.0
tensorboard==2.16.2
tensorboard-data-server==0.7.2
termcolor==2.4.0
threadpoolctl==3.4.0
torch==2.2.2+cu118
torchaudio==2.2.2+cu118
torchvision==0.17.2+cu118
tqdm==4.66.2
transaction==4.0
translationstring==1.4
triton==2.2.0
typing_extensions==4.8.0
tzdata==2024.1
urllib3==2.2.1
velruse==1.1.1
venusian==3.1.0
WebOb==1.8.7
Werkzeug==3.0.2
WTForms==3.1.2
wtforms-recaptcha==0.3.2
yacs==0.1.8
zope.deprecation==5.0
zope.interface==6.3
zope.sqlalchemy==3.1
```

**Comment by q10** [comment]
Hi @momingh I think you have to install CUDA:

```
libcudart.so.12: cannot open shared object file: No such file or directory
```

Please follow the instructions [here](https://pytorch.org/FBGEMM/fbgemm_gpu-development/InstallationInstructions.html) to do this, and let us know if you still run into issues.

**Comment by momingh** [comment]
> 嗨，我认为您必须安装CUDA：
> 
> ```
> libcudart.so.12: cannot open shared object file: No such file or directory
> ```
> 
> 请按照[此处](https://pytorch.org/FBGEMM/fbgemm_gpu-development/InstallationInstructions.html)的说明执行此操作，如果您仍然遇到问题，请告诉我们。

Thank you for your answer. We have replaced the equipment with single A100, and the following errors have occurred. May I ask how to solve them? Our cuda version is 12.1 and we tried to use both cuda11.8 and cuda12.1 versions of pytorch, but both had the same issue.

```
Traceback (most recent call last):
  File "/root/autodl-tmp/generative-recommenders/train.py", line 509, in <module>
    app.run(main)
  File "/root/miniconda3/envs/torch310/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/root/miniconda3/envs/torch310/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/root/autodl-tmp/generative-recommenders/train.py", line 502, in main
    mp.spawn(mp_train_fn,
  File "/root/miniconda3/envs/torch310/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 281, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/root/miniconda3/envs/torch310/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 237, in start_processes
    while not context.join():
  File "/root/miniconda3/envs/torch310/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 188, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/envs/torch310/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 75, in _wrap
    fn(i, *args)
  File "/root/autodl-tmp/generative-recommenders/train.py", line 495, in mp_train_fn
    train_fn(rank, world_size, master_port)
  File "/root/miniconda3/envs/torch310/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/root/miniconda3/envs/torch310/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/root/miniconda3/envs/torch310/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/root/autodl-tmp/generative-recommenders/train.py", line 328, in train_fn
    eval_dict = eval_metrics_v2_from_tensors(
  File "/root/miniconda3/envs/torch310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/generative-recommenders/data/eval.py", line 109, in eval_metrics_v2_from_tensors
    shared_input_embeddings = model.encode(
  File "/root/autodl-tmp/generative-recommenders/modeling/sequential/hstu.py", line 654, in encode
    return self._encode(
  File "/root/autodl-tmp/generative-recommenders/modeling/sequential/hstu.py", line 617, in _encode
    encoded_seq_embeddings, cache_states = self.generate_user_embeddings(
  File "/root/autodl-tmp/generative-recommenders/modeling/sequential/hstu.py", line 554, in generate_user_embeddings
    x_offsets=torch.ops.fbgemm.asynchronous_complete_cumsum(past_lengths),
  File "/root/miniconda3/envs/torch310/lib/python3.10/site-packages/torch/_ops.py", line 1125, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'asynchronous_complete_cumsum'

```

**Comment by momingh** [comment]
> Hi @momingh I think you have to install CUDA:
> 
> ```
> libcudart.so.12: cannot open shared object file: No such file or directory
> ```
> 
> Please follow the instructions [here](https://pytorch.org/FBGEMM/fbgemm_gpu-development/InstallationInstructions.html) to do this, and let us know if you still run into issues.

Thank you for your answer, the issue has been resolved
